development:
  access_key_id: 5YZ6GTZKQQE3982
  secret_access_key: GJRY4vFqy7NfdnuDA77VzWvc4PhxKn94AbpTDhhL
  bucket: nottwitter-avatars
production:
  access_key_id: 5YZ6GTZKQQE3982
  secret_access_key: GJRY4vFqy7NfdnuDA77VzWvc4PhxKn94AbpTDhhL
  bucket: nottwitter-avatars
